#pragma config(Motor,  port3,           scoopServo,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           scoopMotor,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void scoopServoFunction(){
	//Turns servo 45 degrees clockwise if button 6U is pressed
	if(vexRT[Btn6U]) {
		motor[scoopServo]=45;
	}

	//Turns servo 45 degrees counterclockwise if button 6D is pressed
	else if (vexRT[Btn6D]) {
		motor[scoopServo]=0;
	}

}
void scoopMotorFunction(){

	//Turns scoopMotor clockwise if button 5U is pressed
	if (vexRT[Btn5U]) {
		motor[scoopMotor] = 127;
	}

	//Turns scoopMotor counterclockwise if button 5D is pressed
	else if (vexRT[Btn5D]) {
		motor[scoopMotor] = -127;
	}

	//Stops scoopMotor if buttons 5U and 5D aren't being pressed
	else {
		motor[scoopMotor] = 0;
	}
}
task main()
{
	//infinite loop
	while (1==1) {
		scoopServoFunction();
		scoopMotorFunction();
	}

}
