#pragma config(Motor,  port4,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor2,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           doorServo,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           funnelServo,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Function that controls the Arm
void armMotorControl(){

	//Declare and Initialize Ch2 as Vex Controller channel 2, which
	//We can change joystick controls depending on what the driver wants
	int c2 = vexRT[Ch2];
	if (c2<-30||30<c2){
		motor[armMotor] = c2;

		motor[armMotor2] = c2;
		} else {
		motor[armMotor2]=0;
		motor[armMotor]=0;
	}
}

//Function that controls Arcade Drive
void arcadeDrive(){

	int joy_x;            // will hold the X value of the analog stick (choices below)
	int joy_y;            // will hold the Y value of the analog stick (choices below)
	int threshold = 10;

	joy_x = vexRT[Ch4];   // This is the RIGHT analog stick.  For LEFT, change 'Ch1' to 'Ch4'.
	joy_y = vexRT[Ch3];   // This is the RIGHT analog stick.  For LEFT, change 'Ch2' to 'Ch3'.

	// Forward, and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is POSITIVE)
	if(((abs(joy_x) > threshold) || (abs(joy_y) > threshold)) && (joy_y > 0))
	{
		motor[leftMotor]  = (joy_y + joy_x)/2;
		motor[rightMotor] = (joy_y - joy_x)/2;
	}
	// Backwards and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is NEGATIVE)
	else if(((abs(joy_x) > threshold) || (abs(joy_y) > threshold)) && (joy_y < 0))
	{
		motor[leftMotor]  = (joy_y - joy_x)/2;
		motor[rightMotor] = (joy_y + joy_x)/2;
	}
	// Turning in place: (abs(X) is above the threshold, abs(Y) is below the threshold)
	else if((abs(joy_x) > threshold) && (abs(joy_y) < threshold))
	{
		motor[leftMotor]  = joy_x;
		motor[rightMotor] = (-1 * joy_x);
	}
	// Standing still: (both abs(X) and abs(Y) are below the threshold)
	else
	{
		motor[leftMotor]  = 0;
		motor[rightMotor] = 0;
	}
}

//This function controls the servo for the corn door
void doorServoControl(){
	int btn1 = vexRT(Btn5U);
	int btn2 = vexRT(Btn5D);
	if(btn1 == 1){
		motor[doorServo] = 360;
	}
	if(btn2 == 1){
		motor[doorServo] = -360;
	}
}

//Function that controls the door on the seed funnel
void funnelServoControl(){
	int btn4 = vexRT(Btn5U);
	int btn5 = vexRT(Btn5D);
	if(btn4 == 1){
		motor[funnelServo] = 131;
	}
	if(btn5 == 1){
		motor[funnelServo] = -55;
	}
}

//Main body of program
task main{
	while(1==1){
		arcadeDrive();
		armMotorControl();
		doorServoControl();
		funnelServoControl();
	}
}